### ISSUE TITLE
Can't play videos 

### ISSUE THREAD

**Issue by asadul04** [ivan-hc/Opera-appimage#1]
It can't paly videos on most of the sites

**Comment by ivan-hc** [comment]
it seems to be a missing plugin, I've tried to rebuilt it with pkg2appimage including all dependences needed from a normal installation, and it seems to reccommend two optional packages (pepperflashplugin-nonfree, chromium-codecs-ffmpeg-extra, the first one is unsupported, the second one is old).

I've found the same issue into Vivaldi, but I've fixed this by including the inbuilt /libffmpeg.so library.

Also Opera have an inbuilt libffmpeg.so file, but when I run it from terminal I get errors like "unsupported x264". Maybe Opera itself uses an old library for ffmpeg.

Now I'll try to include the one from Vivaldi to see what happens.

**Comment by ivan-hc** [comment]
Just found some sources around and seems to be a known issue:

- https://forums.opera.com/topic/37539/solved-solving-the-problem-of-the-opera-browser-with-video-playback-in-ubuntu-and-similar-distributions-linux-mint-kde-neon/122?lang=en
- http://linuc.hstn.me/en/community/view.php/topic/2022-05-19022752eb8d0?i=1
- https://askubuntu.com/questions/1288996/how-do-i-get-h-264-support-in-opera-in-20-10-installed-via-deb-from-official-si

More banally, Ubuntu is switching all its packages to Snap, Opera developers are using an old ffmpeg in their deb package and none have updated it... so none cares about the deb version of Opera.

All workaround seems to point to external third-party sources.

I suggest not to run the script, because it should replace an hipotetic /usr/lib/x86_64-linux-gnu/opera/libffmpeg.so file that does not exists, being it bundled into the AppImage.

However, until the deb package has no fixes, I can't update the AppImage.

If you need Opera, I'm sorry to say that, use the Snap or Flatpak version.

NOTE: Opera, Vivaldi, Brave, Google Chrome... are all browsers based on Chromium. Alternativelly use another web browser, like Brave or Vivaldi, they are multiplatform, privacy oriented and more supported than Opera (at least on the Linux-side). I've built Vivaldi in the same way, and everything works as expected.

**Comment by ivan-hc** [comment]
@asadul04 solved by adding extra libraries from https://github.com/swanux/opera_codecs
